---
- name: gather-facts
  cisco.ios.ios_facts:
    gather_subset: all
  
- name:
  debug:
    msg:
      - "Hostname: {{ ansible_net_hostname }}"
      - "OS Type: {{ ansible_net_iostype }}"
      - "Model: {{ ansible_net_model }}" 
