---
- name: gather-facts
  cisco.ios.ios_facts:
    gather_subset: hardware
    register: hardware_facts

- name: Display 5-second CPU utilization
  debug:
    msg: "5-second CPU utilization: {{ ios_facts_output.ansible_net_cpu_utilization | default('N/A') }} %"